version: '3'
services:
  django:
    build: ./
    container_name: django-auto
    command: python auto/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
